print("Aylik Masraf Hesaplama Programina Hosgeldiniz")
mutfak=input("mutfak masrafi")
egitim=input("egitim masrafi")
giyim=input("giyim masrafi")
ulasim=input("ulasim masrafi")
aylik_gelir=input("aylik gelir")
toplam_masraf=float(mutfak)+float(egitim)+float(giyim)+float(ulasim)
oran=toplam_masraf/float(aylik_gelir)
print("Toplam Masrafiniz:", toplam_masraf,"\nGelirinize Orani",oran)
dosya=open("Toplammasraf.txt","w")
print("Toplam Masrafiniz:", toplam_masraf,"\nGelirinize Orani",oran,file=dosya)
dosya.close()
