print("Hosgeldiniz\nLutfen Bilgilerinizi Griniz")
print("Ad & Soyad:")
ad_soyad=input()
print("Vize Notunuzu Giriniz:")
vize=input()
print("Final Notunuzu Giriniz:")
final=input()
print("Devamsizlik:")
devamsizlik=input()
yil_sonu_notu=int(vize)*0.3+int(final)*0.5+(100-int(devamsizlik)*5)*0.2
print("Yil Sonu Notunuz:",yil_sonu_notu)
dosya=open("ogrenciNotHesaplama.txt", "w")
print(ad_soyad,vize,final,devamsizlik,yil_sonu_notu,file=dosya)
dosya.close()
