kelime=input()
satir=10+len(kelime)
print(satir*"+")
print("+",(satir-2)*" ","+", sep="")
print("+",4*" ",kelime,4*" ","+", sep="")
print("+",4*" ",len(kelime)*"-",4*" ","+", sep="")
print("+",(satir-2)*" ","+", sep="")
print(satir*"+")
